spring:
  datasource:
    url: jdbc:postgresql://localhost:5432/sweetshop
    username: postgres
    password: "@@@Ditya2010"

  jpa:
    hibernate:
      ddl-auto: update
    show-sql: true

server:
  port: 8081

jwt:
  secret: "9f3c2a4b8d1e6f7a9c2d4e6b8a1f3c5d"
  expiration-ms: 86400000
